apiVersion: v1
kind: Service
metadata:
  name: devops-pt3-service
spec:
  type: NodePort
  selector:
    app: devops-pt3
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      # Fixed external port for testing (30000â€“32767)
      nodePort: 30080